# jfs-demo/my-request-app-chart/templates/backend-webhook-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-request-app-chart.fullname" . }}-backend-webhook-secret
  labels:
    {{- include "my-request-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque # Standard type for arbitrary data
stringData:
  # Generate a strong, random secret. You can use 'head /dev/urandom | tr -dc A-Za-z0-9_ | head -c 20'
  # Set this value in your values.yaml, or directly here if not dynamic.
  # THIS MUST BE THE SAME SECRET YOU CONFIGURE IN GITHUB!
  WebHookSecretKey: {{ .Values.backend.webhookSecret | default (randAlphaNum 20) | quote }}
