# jfs-demo/my-request-app-chart/templates/frontend-webhook-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-request-app-chart.fullname" . }}-frontend-webhook-secret
  labels:
    {{- include "my-request-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
type: Opaque
stringData:
  # Generate a strong, random secret.
  # THIS MUST BE THE SAME SECRET YOU CONFIGURE IN GITHUB!
  WebHookSecretKey: {{ .Values.frontend.webhookSecret | default (randAlphaNum 20) | quote }}
