# jfs-demo/my-request-app-chart/templates/frontend-buildconfig.yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "my-request-app-chart.fullname" . }}-frontend-build
  labels:
    {{- include "my-request-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "my-request-app-chart.fullname" . }}-frontend-image:latest
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.frontend # Path to the Dockerfile in the Git repo
  source:
    type: Git
    git:
      uri: {{ .Values.git.repository }}
      ref: {{ .Values.git.branch }}
    contextDir: {{ .Values.git.contextDir }} # Optional subdirectory
  triggers:
    - type: ConfigChange # Keep this trigger
    # NEW: GitHub Webhook Trigger
    - type: GitHub
      github:
        secretReference:
          name: {{ include "my-request-app-chart.fullname" . }}-frontend-webhook-secret
  runPolicy: Serial
