apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-request-app-chart.fullname" . }}-frontend-service
  labels:
    {{- include "my-request-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "my-request-app-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
